language: ruby
rvm: 2.0.0
env:
  global:
  - secure: obYnCEQ36T5BL1fM241Fk5qlcjaVIw+gkuSECtMuIwl/KlrBbSY25f73x02oYGNY2w/NgvtGGqkLzIEm4PuQQkN70+8ndpnfuhr6y0w+ScfxpGjvD5+hhWQTshhQS7pVYBQ1vQ2BsYnqXOn8jCwhxx+DOkG2tIvhKkBMfW7mlTw=
  - secure: dBRFhXQGakWCpz1FhgXobEfw8x6i5RqNuB0tk96N3rNnANxH3E8VTUPtWM1O0lcDCFL33oclf9tAmRt8TkSo4OrWqD63t9hCM9fnA3EgJhiYR/wi7takRu+gQtrbDvSUMG97z510NzHH3/xCV0Ubjrlw2V/G5kE7s7uDpQxCwPM=
  - secure: k5JNWTjsOROp6PsbuyqjDePrnmRnlp7D68/2VVMup+Db0qxTECUovddEKGCtEaIRoYdGRMliFDi6OSRlG72pktuGuJ0gpznVeLUoMjsyRAkeJfMNx/cNxUkv/qixJU5INPmBPap/2dhIPx5X5f5ubLg2ojTb139pdGUZHmB++tY=
  - secure: A0VZjeyxXE4oYqKlzF0fLuYMegmpl4PM1EIM8L2Dmv0wdmF8obodXSyCw4FDIQYHp13kHqZ+3WAFJ8zg3yUODz3AB55lJGmDx956XTtmgeu1P1LmB9y8+uH4dxW+t+iG06bcdQIPUv76+pe2j1mpymT4gaenrKCHrB4Oe5qckjw=

script:
- bundle exec jekyll build --trace
after_success: bundle exec travis-custom-deploy sftp service:jekyll