# Site settings
title: Antônio Carlos
email: antoniofreitas@inf.ufg.br
description: Mestrado em Ciência da Computação
baseurl: "http://inf.ufg.br/~msc20150217"
url: "http://inf.ufg.br/~msc20150217" 
twitter_username: acarlosfreitas
github_username:  acfreitas
lattes_id:  5551718524873669
nome_citacoes: A C FREITAS
linkedin_username:  acarlosfreitas
stackoverflow_username: acfreitas
stackoverflow_id: 2335712

exclude:
  - 'vendor'
  - 'Gemfile*'
  - 'README.md'
  - '*.yml'
  - 'LICENSE'

# Build settings
markdown: kramdown