# Site settings
title: Antônio Freitas
email: antoniofreitas@inf.ufg.br
description: Mestrado em Ciência da Computação
baseurl: ""
url: "http://inf.ufg.br/~antoniofreitas/" 
twitter_username: acarlosfreitas
github_username:  acfreitas

exclude:
  - 'vendor'
  - 'Gemfile*'
  - 'README.md'
  - '*.yml'
  - '*.sass'
  - '*.scss'
  
# Build settings
markdown: kramdown